// <auto-generated />
namespace My_Shop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _100121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_100121));
        
        string IMigrationMetadata.Id
        {
            get { return "202101101423504_10.01.21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
