// <auto-generated />
namespace My_Shop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20jun3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20jun3));
        
        string IMigrationMetadata.Id
        {
            get { return "202101202145082_20jun3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
