// <auto-generated />
namespace My_Shop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _21jan1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21jan1));
        
        string IMigrationMetadata.Id
        {
            get { return "202101212152477_21jan1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
